import type { ReviewTemplate } from "./types"

export const REVIEW_TEMPLATES: ReviewTemplate[] = [
  {
    id: "pool-vineyard",
    requiredAmenities: ["pool", "vineyard-view"],
    es: "La alberca con vista al viñedo al atardecer fue el momento más memorable del viaje. Todo impecable y muy tranquilo.",
    en: "The pool with vineyard views at sunset was the most memorable moment of the trip. Everything was spotless and wonderfully peaceful.",
  },
  {
    id: "pool-jacuzzi",
    requiredAmenities: ["pool", "jacuzzi"],
    es: "Alternar entre la alberca y el jacuzzi después de recorrer viñedos fue exactamente la escapada que buscábamos.",
    en: "Going between the pool and jacuzzi after touring the vineyards was exactly the escape we were looking for.",
  },
  {
    id: "pool-only",
    requiredAmenities: ["pool"],
    es: "La alberca privada al atardecer, con el valle en calma, hizo que no quisiéramos salir de la propiedad.",
    en: "The private pool at sunset, with the valley completely still, made us never want to leave the property.",
  },
  {
    id: "jacuzzi-only",
    requiredAmenities: ["jacuzzi"],
    es: "Terminar cada día en el jacuzzi bajo el cielo del valle fue el ritual perfecto después de las degustaciones.",
    en: "Ending each day in the jacuzzi under the valley sky was the perfect ritual after wine tastings.",
  },
  {
    id: "fire-pit",
    requiredAmenities: ["fire-pit"],
    es: "Las noches junto a la fogata, con vino local y el silencio del valle, se sintieron mágicas de principio a fin.",
    en: "Evenings by the fire pit with local wine and the silence of the valley felt magical from start to finish.",
  },
  {
    id: "terrace-view",
    requiredAmenities: ["terrace", "vineyard-view"],
    es: "Desayunar en la terraza con esa vista al valle es algo que repetiríamos sin pensarlo.",
    en: "Breakfast on the terrace with that valley view is something we'd repeat without hesitation.",
  },
  {
    id: "vineyard-view",
    requiredAmenities: ["vineyard-view"],
    es: "Despertar con los viñedos a la vista y el valle envuelto en neblina fue una experiencia que vale cada kilómetro del viaje.",
    en: "Waking up to vineyard views and the valley wrapped in morning mist was worth every mile of the trip.",
  },
  {
    id: "wine-cellar",
    requiredAmenities: ["wine-cellar"],
    es: "Tener una cava de vinos en la propiedad elevó toda la estancia — perfecto para cerrar las noches con una copa del valle.",
    en: "Having a wine cellar on property elevated the whole stay — perfect for ending nights with a glass from the valley.",
  },
  {
    id: "spa",
    requiredAmenities: ["spa"],
    es: "El spa privado después de un día entre viñedos fue el contraste perfecto entre aventura y descanso total.",
    en: "The private spa after a day among the vineyards was the perfect contrast between adventure and total rest.",
  },
  {
    id: "pet-friendly",
    requiredAmenities: ["pet-friendly"],
    es: "Poder traer a nuestra mascota y que estuviera tan cómoda como nosotros habla muy bien del lugar y del anfitrión.",
    en: "Being able to bring our pet and have them as comfortable as we were says a lot about the place and the host.",
  },
  {
    id: "breakfast",
    requiredAmenities: ["breakfast"],
    es: "El desayuno incluido con productos locales fue un detalle que marcó la diferencia cada mañana.",
    en: "Breakfast included with local products was a detail that made every morning special.",
  },
  {
    id: "bbq-patio",
    requiredAmenities: ["bbq", "patio"],
    es: "Preparar la cena en el asador del patio, con el aire fresco del valle, fue uno de los mejores momentos del fin de semana.",
    en: "Cooking dinner on the patio grill with the cool valley air was one of the best moments of the weekend.",
  },
  {
    id: "bbq-only",
    requiredAmenities: ["bbq"],
    es: "El asador estuvo listo para usarse y compartir una cena al aire libre con amigos fue increíble.",
    en: "The grill was ready to go and sharing an outdoor dinner with friends was incredible.",
  },
  {
    id: "patio",
    requiredAmenities: ["patio"],
    es: "El patio se convirtió en nuestro rincón favorito para leer, tomar café y desconectarnos por completo.",
    en: "The patio became our favorite spot to read, have coffee, and fully unplug.",
  },
  {
    id: "wifi-terrace",
    requiredAmenities: ["wifi", "terrace"],
    es: "Trabajamos un par de horas en la terraza con excelente wifi y el resto del día fue puro valle — el equilibrio perfecto.",
    en: "We worked a couple of hours on the terrace with great wifi and spent the rest of the day in the valley — perfect balance.",
  },
  {
    id: "terrace-only",
    requiredAmenities: ["terrace"],
    es: "La terraza al atardecer, con una copa de vino, resume por qué volvemos una y otra vez al Valle de Guadalupe.",
    en: "The terrace at sunset with a glass of wine sums up why we keep coming back to Valle de Guadalupe.",
  },
  {
    id: "pool-fire",
    requiredAmenities: ["pool", "fire-pit"],
    es: "Día de alberca y noche de fogata: la combinación ideal para desconectar en el valle.",
    en: "Pool days and fire pit nights — the ideal combo to unplug in the valley.",
  },
  {
    id: "jacuzzi-vineyard",
    requiredAmenities: ["jacuzzi", "vineyard-view"],
    es: "El jacuzzi con vista al viñedo al anochecer es de esos detalles que no olvidas.",
    en: "The jacuzzi overlooking the vineyard at dusk is one of those details you don't forget.",
  },
  {
    id: "generic-host-1",
    requiredAmenities: [],
    es: "Impecable de principio a fin. El anfitrión atento, la propiedad tal como en las fotos y las recomendaciones del valle fueron un plus enorme.",
    en: "Flawless from start to finish. An attentive host, the property exactly as pictured, and valley recommendations were a huge plus.",
  },
  {
    id: "generic-host-2",
    requiredAmenities: [],
    es: "Check-in sencillo, espacios limpios y una energía muy especial. Se nota el cuidado en cada detalle.",
    en: "Easy check-in, clean spaces, and a very special feel. You can tell every detail was cared for.",
  },
  {
    id: "generic-valley-1",
    requiredAmenities: [],
    es: "La tranquilidad del valle, la calidad del alojamiento y el servicio hicieron de este un viaje que repetiremos pronto.",
    en: "The peace of the valley, the quality of the stay, and the service made this a trip we'll repeat soon.",
  },
  {
    id: "generic-valley-2",
    requiredAmenities: [],
    es: "Perfecto para una escapada de fin de semana: ubicación, comodidad y esa sensación de estar lejos de todo sin sacrificar nada.",
    en: "Perfect for a weekend escape: location, comfort, and that feeling of being far from everything without giving anything up.",
  },
  {
    id: "generic-wine-1",
    requiredAmenities: [],
    es: "Entre viñedos, buena comida y una estancia sin fallas — exactamente lo que buscábamos en Valle de Guadalupe.",
    en: "Between vineyards, great food, and a flawless stay — exactly what we wanted in Valle de Guadalupe.",
  },
  {
    id: "generic-family-1",
    requiredAmenities: [],
    es: "Viajamos en familia y todos quedamos encantados. Espacios amplios, todo muy cuidado y un ambiente relajado.",
    en: "We traveled as a family and everyone loved it. Spacious rooms, everything well kept, and a relaxed atmosphere.",
  },
  {
    id: "generic-couple-1",
    requiredAmenities: [],
    es: "Ideal para una escapada en pareja. Íntimo, bonito y con esa calma que solo el valle te da.",
    en: "Ideal for a couples getaway. Intimate, beautiful, and with that calm only the valley gives you.",
  },
]
